package http

import (
	v1handlers "github.com/codevshl/http-metadata-inventory-service/internal/adapters/primary/http/handlers/v1"
	"github.com/codevshl/http-metadata-inventory-service/internal/adapters/primary/http/middleware"
	"github.com/codevshl/http-metadata-inventory-service/internal/core/ports"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "github.com/codevshl/http-metadata-inventory-service/docs"
)

// SetupRouter configures the Gin engine and routes
func SetupRouter(svc ports.MetadataService, isProd bool) *gin.Engine {
	if isProd {
		gin.SetMode(gin.ReleaseMode)
	}

	r := gin.New()

	// Apply Middlewares
	r.Use(middleware.TraceMiddleware())
	r.Use(middleware.RequestLogger())
	r.Use(middleware.RecoveryMiddleware())
	r.Use(middleware.JSONMiddleware())

	// TODO: we definitely need to add some auth here later (JWTs or API keys)
	// so we don't leave the API wide open. this would also let us do rate
	// limiting per user which is super important for production.
	r.Use(middleware.ErrorHandlerMiddleware())

	// Handlers
	metadataHandler := v1handlers.NewMetadataHandler(svc)

	// Routes
	v1 := r.Group("/api/v1")
	{
		v1.POST("/metadata", metadataHandler.CreateMetadataHandler)
		v1.GET("/metadata", metadataHandler.GetMetadataHandler)
	}

	// Health check
	r.GET("/health", v1handlers.HealthHandler)

	// Swagger docs (auto-generated by swag)
	r.GET("/docs/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	return r
}
